---
title: "Revealjs"
author: "Rafaela Becerra"
date: "February 2020"
output: 
  revealjs::revealjs_presentation:
  theme: moon
  incremental: true
  highlight: pygments
  center: true

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Dataset {data-transition="zoom"}
<section data-background="image.jpg">
Data from cars.com in 2017 for a sample of 90 cars in Ohio of three models:
<span style="display: inline-block;" class="fragment fade-up" data-fragment-index="1">Mazda 6, </span>
<span style="display: inline-block;" class="fragment fade-down" data-fragment-index="2">Honda Accord, </span>
<span style="display: inline-block;" class="fragment fade-left" data-fragment-index="3">and Toyota Maxima.</span>
</section>

<section data-transition="zoom">
## Summary 
```{r, include = FALSE}
library(Stat2Data)
data("ThreeCars2017")
data=ThreeCars2017
```

```{r, echo=FALSE}
library(skimr)
datas=skim(data)
```

## Variables
The information contained is:

- Bullet 1
- Bullet 2
- Bullet 3

</section>

## Characteristics
```{r, include=FALSE}
library(plotly)
```

```{r, echo=FALSE, warning=FALSE}
p <- plot_ly(data, x = ~Age, y = ~Price, z = ~Mileage, color = ~CarType) %>%
   add_markers()%>%layout(scene = list(xaxis = list(title = 'Age from production'),
                     yaxis = list(title = 'Price in $1,000'),
                     zaxis = list(title = 'Mileage in km')))
p

```

